[project]
name = "ict-mvp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.3",
    "pandas-stubs~=2.3.3",
    "requests>=2.32.5",
    "ruff>=0.14.10",
]
